// import Header from "@/components/Header";
// import Footer from "@/components/Footer";
// import HeadHomepage from "@/components/head/HeadHomepage";
// import HomeBody from "@/components/HomeBody";
// import { Suspense } from "react";
// // import { DarkThemeToggle, Flowbite } from "flowbite-react";
// export async function generateMetadata({ params }) {
//     return {
//         title: "...1",
//         description: "Generated by create next app",
//     };
// }
// export const experimental_ppr = true;
// export default function Home() {
//     var props = {
//         admin_path: process.env.ADMIN_PATH,
//         siteInfo: {
//             keyword: [],
//         },
//         title: "asas",
//     };
//     return (
//         <>
//             {" "}
//             {/* <Flowbite> */}
//                 {/* <DarkThemeToggle className="float-right" /> */}
//                 <HeadHomepage siteInfo={{ ...props.siteInfo }} title={"abc"} />
//                 <Header {...props} />
//                 <HomeBody {...props} />
//                 <Suspense>
//                     <Footer {...props} />
//                 </Suspense>{" "}
//             {/* </Flowbite> */}
//         </>
//     );
// }
import Quill from "quill";
import { component$, useVisibleTask$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";

export default component$(() => {
  // const props = {
  //     admin_path: process.env.ADMIN_PATH,
  //     categories:[]
  // };
  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(() => {
    // const quill = new Quill('#editor', {
    //     theme: 'snow'
    //   });
    function imageHandler() {
        const input = document.createElement('input');
        input.setAttribute('type', 'file');
        input.click();

        // Listen upload local image and save to server
        input.onchange = () => {
        const file = input.files[0];

        // file type is only image.
        if (/^image\//.test(file.type)) {
          saveToServer(file);
        } else {
        console.warn('You could only upload images.');
        }
        };
    //   var range = this.quill.getSelection();
    //   var value = prompt("please copy paste the image url here.");
    //   if (value) {
    //     this.quill.insertEmbed(
    //       range.index,
    //       "image",
    //       value,
    //       Quill.sources.USER,
    //     );
      }
    function saveToServer(f){
        console.log("up");
        
    }
    const quill = new Quill("#editor", {
      debug: "info",
      modules: {
        toolbar: {
          container: [
            ["bold", "italic", "underline", "strike"],
            ["blockquote", "code-block"],
            [{ 'size': ['small', false, 'large', 'huge'] }],
            [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
            [{ color: ["blue","OrangeRed", "green","lime","yellow","white","gray","black","orange","gold","MediumSlateBlue","brown"] }, { background: [] }],
            [{ font: [] }],
            [{ align: [] }],

            ["clean"],
            ["image"], //add image here
            ["video"],
            ["link"],
          ],
          handlers: {
            video: function videoHandler() {
              var range = this.quill.getSelection();
              var value = prompt("please copy paste the video url here.");
              if (value) {
                this.quill.insertEmbed(
                  range.index,
                  "video",
                  value,
                  Quill.sources.USER,
                );
              }
            },
            image:imageHandler ,
            link: function (value) {
                if (value) {
                  const href = prompt('Enter the URL');
                  this.quill.format('link', href);
                } else {
                  this.quill.format('link', false);
                }
              }
          },
        },
      },
      placeholder: "Compose an epic...",
      theme: "snow",
    });
    const customButton = document.querySelector('#custom-button');
    customButton.addEventListener('click', function (e) {
        e.preventDefault()
      console.log('Clicked!');
      fetch("/media/upload",{
        method:"POST",
        body:"A"
      })
    });
  });
  return (
    <>
      <div>
        <link
          href="https://cdn.jsdelivr.net/npm/quill@2.0.2/dist/quill.snow.css"
          rel="stylesheet"
        />
<div id="toolbar">
<input type="file" multiple />
  <button id="custom-button">Upload image</button>
</div>
        <div id="editor">
          {/* <p>Hello World!</p>
          <p>
            Some initial <strong>bold</strong> text
          </p> */}
          {/* <p>
            <br />
          </p> */}
        </div>
      </div>
    </>
  );
});
export const head: DocumentHead = ({ resolveValue, params }) => {
  return {
    title: "Welcome to Qwik",
    meta: [
      {
        name: "description",
        content: "Qwik site description",
      },
    ],
  };
};
